<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo isset($title)?$title:'soquair';?></title>
</head>

<body>
    <style>
.team_list h2 {
height: 20px;
line-height: 20px;
margin: 10px 0 0 0;
padding-left: 8px;
font-size: 12px;
font-weight: bold;
color: #333;
}
#mediashow2 li {
list-style: none;
float: left;
padding: 2px 10px 2px 0;
}
#mediashow2 li a {
width: 50px;
height: 50px;
display: block;
}
.denglu_icon2 {
width: 50px;
height: 50px;
text-indent: -999em;
display: block;
background: url(/res/img/denglu_icon2_all_bg.png) no-repeat scroll 0 0 transparent;
}
.denglu_icon2_qq{
background-position: 0 -600px;
}
.denglu_icon2_weibo{
background-position: 0 -120px;
}
    </style>
    <div class="team_list">
        <h2>合作网站账号登录</h2>
        <div id="slideshow2" class="team_con" style=""><a class="team_left2" id="leftControl2" href="javascript:;" style="display: none; top: 81px;"></a><a class="team_left1" id="leftNoLink2" style="top: 81px; visibility: hidden;"></a>
            <div id="slidesContainer2" class="teamcon" style="overflow: hidden; width: 300px; height: 180px;">
                <div id="slideInner2" style="width: 300px;">
                    <div id="mediashow2" class="denglu_con">
                        <ul>
                            <li>
                                <a href="/media_qq/?app_id=69948denMVMoBujYGLSFGUHbkvP7E3" target="_blank" title="用QQ登陆" class="denglu_icon2 denglu_icon2_qq"></a>
                            </li>
                            <li>
                                <a href="/media_weibo/?app_id=69948denMVMoBujYGLSFGUHbkvP7E3" target="_blank" title="用QQ登陆" class="denglu_icon2 denglu_icon2_weibo"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div></div></div>
</body>
</html>


