<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo isset($title)?$title:'soquair';?></title>
</head>

<body>
    <span id="qqLoginBtn"></span>
    <a href="/media_qq/?app_id=<?php echo $appid;?>"><img src="/res/img/QQ_5.png"></a>
</body>
</html>


